/**
 * Type declaration for the static JSON import of the Ledger-owned exercise
 * catalog (LG-047). `exercises.json` is generated by the curation pipeline
 * in `scripts/curation/` from a `free-exercise-db` seed - see
 * `.gsd/exercise-model.md`.
 *
 * Declared here (relying on `allowArbitraryExtensions`) instead of enabling
 * `resolveJsonModule`, which would make tsc infer a huge literal type from
 * the ~1MB `exercises.json` file.
 */
import type { Exercise } from './types'

declare const exercises: Exercise[]
export default exercises
